<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE member_list [
<!ELEMENT member_list (member+)>
<!ELEMENT member (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT office (#PCDATA)>
<!ELEMENT join_date (#PCDATA)>
<!ELEMENT years (#PCDATA)>
]>
<member_list>
  <member>
    <institution>University of Minnesota</institution>
    <first_name>Goldy<first_name>
    <last_name>Gopher<last_name>
    <phone>999-999-9999</phone>
    <email>goph3r@umn.edu</email>
    <office>Admissions</office>
    <join_date>January 01, 1940</join_date>
    <years>78</years>
  </member>
</member_list>
